[package]
name = "cartoonist-auction"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.32"
anchor-spl = "0.32"
blake3 = { workspace = true }

[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
